Repository WebOfTrustInfo/rwot9-prague, pull requests merged in 2019-08, with the labels that each got.

#57 submitting "A Web of Credit Framework"
  topics-and-advance-readings/README.md
  topics-and-advance-readings/web-of-credit.md
Labels: Just needs merge conflict resolution

#40 paper submit
  topics-and-advance-readings/README.md
  topics-and-advance-readings/X.509-DID-Method.md
Labels: needs merge conflict resolution

#69 Create rough draft of Reputation Loops
  topics-and-advance-readings/reputation-loops.md
Labels: need abstract and link

#56 Reimagining global
  topics-and-advance-readings/README.md
  topics-and-advance-readings/reimagining-global-rwot9.md
Labels: needs merge conflict resolution

#30 Update README.md
  topics-and-advance-readings/README.md
Labels: needs merge conflict resolution

#32 RWOT9 Contribution - Credential Issuer-related Protocols
  topics-and-advance-readings/README.md
  topics-and-advance-readings/vc_protocols_issuer.md
  topics-and-advance-readings/vc_protocols_issuer/vc_protocols_issuer-1.png
  topics-and-advance-readings/vc_protocols_issuer/vc_protocols_issuer-2.png
  topics-and-advance-readings/vc_protocols_issuer/vc_protocols_issuer.png
Labels: needs merge conflict resolution
